### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by henosch** [jacklul/rclone-backup#1]
I get this issue on a Pi 4 with Debian 10.

$ sudo rclone-backup
Backing up now...
2021/05/18 17:04:27 ERROR : etc/printcap: Listing error: symlink: stat /etc/printcap: no such file or directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/dovecot.socket: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups.path: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/dovecot.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups.socket: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/postfix.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/samba-ad-dc.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups-browsed.service: Can't transfer non file/directory
2021/05/18 17:04:27 ERROR : sftp://user52@server.net:22/: not deleting files as there were IO errors
2021/05/18 17:04:27 ERROR : sftp://user52@server.net:22/: not deleting directories as there were IO errors
2021/05/18 17:04:27 ERROR : Attempt 1/3 failed with 2 errors and: not deleting files as there were IO errors
2021/05/18 17:04:27 ERROR : etc/printcap: Listing error: symlink: stat /etc/printcap: no such file or directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/dovecot.socket: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups.path: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/dovecot.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups.socket: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/postfix.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/samba-ad-dc.service: Can't transfer non file/directory
2021/05/18 17:04:27 NOTICE: etc/systemd/system/cups-browsed.service: Can't transfer non file/directory
2021/05/18 17:04:28 ERROR : sftp://user52@server.net:22/: not deleting files as there were IO errors
2021/05/18 17:04:28 ERROR : sftp://user52@server.net:22/: not deleting directories as there were IO errors
2021/05/18 17:04:28 ERROR : Attempt 2/3 failed with 2 errors and: not deleting files as there were IO errors
2021/05/18 17:04:28 ERROR : etc/printcap: Listing error: symlink: stat /etc/printcap: no such file or directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/dovecot.socket: Can't transfer non file/directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/cups.path: Can't transfer non file/directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/dovecot.service: Can't transfer non file/directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/cups.socket: Can't transfer non file/directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/postfix.service: Can't transfer non file/directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/cups.service: Can't transfer non file/directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/samba-ad-dc.service: Can't transfer non file/directory
2021/05/18 17:04:28 NOTICE: etc/systemd/system/cups-browsed.service: Can't transfer non file/directory
2021/05/18 17:04:28 ERROR : sftp://user52@server.net:22/: not deleting files as there were IO errors
2021/05/18 17:04:28 ERROR : sftp://user52@server.net:22/: not deleting directories as there were IO errors
2021/05/18 17:04:28 ERROR : Attempt 3/3 failed with 2 errors and: not deleting files as there were IO errors
2021/05/18 17:04:28 INFO  :
Transferred:             0 / 0 Bytes, -, 0 Bytes/s, ETA -
Errors:                 2 (retrying may help)
Checks:                42 / 42, 100%
Elapsed time:         1.6s

2021/05/18 17:04:28 Failed to sync with 2 errors: last error was: not deleting files as there were IO errors

$

And this is my backup.list

**Comment by jacklul** [comment]
You didn't post backup.list, it looks to me like it's rclone configuration mistake.

**Comment by henosch** [comment]
Hello, 
here are my backup list. 
```
# Exclude hidden files and directories
- .*
- .*/**

# pihole update blocklist
+ /etc/pihole/myblocklist.sh
+ /etc/pihole/update_myblocklist.sh 

# Pi-hole
+ /etc/pihole/setupVars.conf
+ /etc/pihole/pihole-FTL.conf
+ /etc/pihole/local.list
+ /etc/pihole/custom.list
+ /etc/pihole/logrotate
+ /etc/dnsmasq.d/*.conf
#+ /etc/lighttpd/lighttpd.conf
+ /etc/cron.d/pihole
+ /etc/systemd/system/pihole-FTL.service
+ /etc/systemd/system/pihole-FTL.service.d/override.conf
+ /etc/pihole/gravity.min.db

# Unbound
+ /etc/unbound/unbound.conf.d/*.conf
+ /etc/systemd/system/unbound.service
+ /etc/systemd/system/unbound.service.d/override.conf

# DNSCrypt
#+ /etc/dnscrypt-proxy/dnscrypt-proxy.toml
#+ /etc/systemd/system/dnscrypt-proxy.service
#+ /etc/systemd/system/dnscrypt-proxy.service.d/override.conf

# Cloudflared
#+ /etc/cloudflared/config.yaml
#+ /etc/default/cloudflared
#+ /etc/systemd/system/cloudflared.service
#+ /etc/systemd/system/cloudflared.service.d/override.conf

# This backup script
+ /etc/rclone-backup/backup.list
+ /etc/rclone-backup/rclone-backup.conf
+ /etc/rclone-backup/script.sh
+ /etc/rclone-backup/rclone.conf

# User entries should go below this line


# Exclude everything else
# DO NOT REMOVE
- **
```

**Comment by henosch** [comment]
For what I can use the rclone-backup.conf? You wrote I must do this: 
```
"Please run 'sudo rclone config --config /etc/rclone-backup/rclone.conf' and set up a remote with name 'remote'!"
```

and in your rclone-backup.sh is this: 

```
CONFIG_FILE=${CONFIG_DIR}/rclone-backup.conf
```
What can I do with this file? 
The rclone settings are in rclone.conf

**Comment by jacklul** [comment]
The config you posted seems ok.
The errors are not caused by my script but by rclone so I suggest you open issue ticket on their repository.

> For what I can use the rclone-backup.conf? You wrote I must do this:
> 
> ```
> "Please run 'sudo rclone config --config /etc/rclone-backup/rclone.conf' and set up a remote with name 'remote'!"
> ```

This generates config used by the rclone command inside the script.

> and in your rclone-backup.sh is this:
> 
> ```
> CONFIG_FILE=${CONFIG_DIR}/rclone-backup.conf
> ```

This is the generated config from above.

The point of this config is to not interfere with any other global configs in case user is using rclone for other purposes.
